# Generated by Django 4.2 on 2023-07-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageClass',
            new_name='Image',
        ),
    ]
